# Generated by Django 5.2.1 on 2025-05-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='supabase_uid',
            field=models.CharField(blank=True, help_text="UID de l'utilisateur dans Supabase", max_length=255, null=True, unique=True),
        ),
    ]
